from typing import Any
from uuid import UUID

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.article import Article
from app.models.asset import ArticleAsset
from app.security.redaction import redact_value
from app.services.runtime_events import record_runtime_event


def register_artifact(
    db: Session,
    *,
    article_id: UUID,
    values: dict[str, Any],
    actor_user_id: UUID | None,
) -> ArticleAsset:
    if db.get(Article, article_id) is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Article not found")
    redacted = {}
    for key, value in values.items():
        # Local artifact paths are generated by the backend; redacting generic
        # 6-digit sequences can corrupt UUID-based paths and break retrieval.
        redacted[key] = value if key == "local_path" else redact_value(value)
    artifact = ArticleAsset(article_id=article_id, **redacted)
    db.add(artifact)
    db.flush()
    record_runtime_event(
        db,
        event_type="artifact.registered",
        actor_type="admin" if actor_user_id else "system",
        actor_user_id=actor_user_id,
        article_id=article_id,
        run_id=artifact.run_id,
        job_id=artifact.job_id,
        message="Artifact registered",
        payload={"asset_id": str(artifact.id), "asset_type": artifact.asset_type, "role": artifact.role},
    )
    return artifact
