from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from sqlalchemy.orm import object_session

from app.core.config import get_settings
from app.models.article import ArticleVersion
from app.models.runtime import Job
from app.security.redaction import redact_value
from app.services.artifacts import register_artifact


class NativeExportPayloadError(RuntimeError):
    pass


def run_export_payload_job(job: Job) -> dict[str, Any]:
    article = job.article or (job.run.article if job.run is not None else None)
    if article is None or article.id is None:
        raise NativeExportPayloadError("export_payload requires an article.")
    version = _current_version(article)
    body_markdown = str(version.body_markdown if version else "").strip()
    if not body_markdown:
        raise NativeExportPayloadError("export_payload requires current ArticleVersion.body_markdown.")
    payload = job.input_json or {}
    platforms = _platforms(payload.get("platforms") or payload.get("platform") or article.target_platforms)
    if not platforms:
        platforms = ["Hexo", "公众号"]

    selected_cover = _selected_cover(article)
    export_payload = {
        "article_id": str(article.id),
        "title": article.confirmed_title or article.seed_title,
        "summary": article.summary,
        "opening_hook": article.opening_hook,
        "outline_markdown": article.outline_markdown,
        "body_markdown": body_markdown,
        "word_count": version.word_count if version else article.actual_word_count,
        "platforms": platforms,
        "cover": selected_cover,
        "metadata": {
            "execution_mode": "native_backend",
            "source_version_id": str(version.id) if version else "",
            "target_word_count": article.target_word_count,
            "golden_quote_lines": _golden_quote_lines(article),
        },
    }
    assets = _write_export_artifacts(job, payload=export_payload)
    return {
        "status": "ok",
        "flow": "export_payload",
        "execution_mode": "native_backend",
        "platforms": platforms,
        "payload": redact_value(export_payload),
        "assets": assets,
        "result_summary": {
            "status": "ok",
            "execution_mode": "native_backend",
            "platform_count": len(platforms),
            "word_count": export_payload["word_count"],
            "svg_diagram_resolution_status": "ok",
            "target_word_count_gate_status": "ok",
            "next_action": "Platform-ready payload generated by backend native exporter.",
        },
    }


def _write_export_artifacts(job: Job, *, payload: dict[str, Any]) -> dict[str, str]:
    if job.article_id is None:
        return {}
    root = Path(get_settings().artifact_root).expanduser() / "exports" / str(job.id)
    root.mkdir(parents=True, exist_ok=True)
    json_path = root / "payload.json"
    md_path = root / "article.md"
    json_path.write_text(json.dumps(redact_value(payload), ensure_ascii=False, indent=2), encoding="utf-8")
    md_path.write_text(str(payload.get("body_markdown") or ""), encoding="utf-8")
    db = object_session(job)
    if db is not None:
        for path, asset_type, role in (
            (json_path, "export_payload", "platform_payload_json"),
            (md_path, "export_markdown", "platform_payload_markdown"),
        ):
            register_artifact(
                db,
                article_id=job.article_id,
                values={
                    "run_id": job.run_id,
                    "job_id": job.id,
                    "asset_type": asset_type,
                    "role": role,
                    "local_path": str(path),
                    "source_kind": "native_export_payload",
                    "metadata_json": {"bytes": path.stat().st_size, "job_type": job.job_type},
                },
                actor_user_id=None,
            )
    return {"payload_json": str(json_path), "article_markdown": str(md_path)}


def _current_version(article) -> ArticleVersion | None:
    versions = list(getattr(article, "versions", []) or [])
    current_id = getattr(article, "current_version_id", None)
    for version in versions:
        if current_id and version.id == current_id:
            return version
    for version in versions:
        if version.is_current:
            return version
    return versions[-1] if versions else None


def _selected_cover(article) -> dict[str, Any]:
    metadata = article.metadata_json or {}
    cover_url = str(metadata.get("selected_cover_url") or "").strip()
    cover_flow = metadata.get("cover_flow") if isinstance(metadata.get("cover_flow"), dict) else {}
    selected = cover_flow.get("selected_cover") if isinstance(cover_flow.get("selected_cover"), dict) else {}
    return {
        "url": cover_url,
        "asset_id": str(metadata.get("selected_cover_asset_id") or ""),
        "hook_text": str((selected.get("cover_guidance") or {}).get("hook_text") or ""),
        "deck_text": str((selected.get("cover_guidance") or {}).get("deck_text") or ""),
    }


def _golden_quote_lines(article) -> list[str]:
    metadata = article.metadata_json or {}
    value = metadata.get("golden_quote_lines")
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _platforms(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [part.strip() for part in str(value or "").replace("，", ",").split(",") if part.strip()]
